### PR TITLE
some comments up to job

### PR DESCRIPTION
**Pull request by vekk513**
Gonna merge conflict but I'll fix

### CODE REVIEW

**Comment by walkhh** [comment]
"NOTE: THIS DOES NOT REMOVE THE VOLUNTEER FROM THE JOB'S LIST!"
Does this mean its a todo/bug or just a note?

**Comment by vekk513** [comment]
Fixed conflicts, good to merge @walkhh @Saerith 

Also @walkhh it's a note; previously it would do both in the same method but now the user must add the job to the jobcollection separately.

**Comment by walkhh** [comment]
For are2DatesOnSameDay parameter tags were removed

**Comment by vekk513** [comment]
Fixed the parameters missing @walkhh

**Pull request merged**
