### PR TITLE
Sequential job ids, jobcollection refactor, removal of light/med/heavy volunteers

### PR DESCRIPTION
**Pull request by vekk513**
Replaced random job ids with sequential jobids to prevent race conditions in the test methods. Also refactored the jobcollection tests and ensured they all pass.

From here: Do the submitjobtests need to exist? They are the same as the jobcollection currently, is there anything that needs to be tested there? 

Also, beyond this I could use another piece of code to work on for the next few days, ping me on discord with something and I'll pick it up.

### CODE REVIEW

**Comment by vekk513** [comment]
@Saerith @vats96ashu @abderisaq @walkhh

**Comment by walkhh** [comment]
If submitJobTest doesn't serve a unique purpose in testing submitting a job that can't be accomplished by testing individual methods, delete it... unless the original author of it has a good reason for having it.
currentJobId shouldn't be in constants - it changes often! It should be loaded from the joblist file, or just inferred from the job list size.

**Comment by vekk513** [comment]
@walkhh @Saerith Pushed two commits moving the jobid functionality to jobcollection (kept the default job id in constants to allow us to change it later if we want to start somewhere other than 0). Also deleted the submitjobtest since all the tests there are contained within jobcollection test

**Comment by walkhh** [comment]
Can you set currentJobId to 0 in the JobCollection constructor? Doing this would prevent a lot of possible errors (currently a JobCollection can have a non-instantiated currentJobId)

**Comment by vekk513** [comment]
Yes, don't know how I missed that thank you. Nice catch.

On Mar 3, 2018 3:31 PM, "walkhh" <notifications@github.com> wrote:

Can you set currentJobId to 0 in the JobCollection constructor? Doing this
would prevent a lot of possible errors (currently a JobCollection can have
a non-instantiated currentJobId)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Saerith/TCSS360Group3/pull/43#issuecomment-370188346>,
or mute the thread

**Comment by vekk513** [comment]
@walkhh Change is implemented, anything else look off about it?

**Pull request merged**
