### PR TITLE
Alec

### PR DESCRIPTION
**Pull request by vekk513**
Initial coding of the collections. Have no idea if the constants class is even working, eclipse doesn't highlight it colorful colors like it normally does, maybe I'm dumb. 

Any suggestions/changes needing to be made on these collections for this deliverable?

ALSO I noticed we didn't have a job name field so I did it by park name, would it be beneficial to have a job name field?

### CODE REVIEW

**Comment by vekk513** [comment]
Sorry I just committed everything not realizing that was a thing.

As for the key, the purpose of the JobCollection is to return a job object via whatever we search it as, so we can't use the job as the key. I'm not quite sure what to make a key unless we have some sort of job ID, or enforce unique titles of jobs.

**Comment by walkhh** [comment]
Oops, I meant to write that you could generate a hash of all fields in Job as an INT, and have that be the key.
The downside to that is if users later neeeded the ability to edit job fields it would break horribly.
Or use sequential/random IDs, I think either 1 could work.

**Comment by walkhh** [comment]
Alright I'm gonna get this working with Volunteer/mainView

**Comment by vekk513** [comment]
Alyssa and I are chatting back and forth on Discord trying to finalize the
running of it. Hopefully we don't step over each other too much ^^

Alec

On Feb 11, 2018 10:11 PM, "walkhh" <notifications@github.com> wrote:

Alright I'm gonna get this working with Volunteer/mainView

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Saerith/TCSS360Group3/pull/7#issuecomment-364836265>,
or mute the thread

**Comment by walkhh** [comment]
So what can I work on to help right now?

**Comment by vekk513** [comment]
Alyssa made an open issue for the volunteer class, check it out.

**Comment by walkhh** [comment]
Are you guys running this code?

**Comment by Saerith** [comment]
It works for me, yeah.

**Comment by walkhh** [comment]
In Main for example it's package is coded as "view" but it is in the directory urbanparks/view. I must be missing something here

**Pull request merged**
