### PR TITLE
Feat/pending jobs count

### PR DESCRIPTION
**Pull request by vekk513**
Quick update adding a function to count the pending jobs in the system. Size is retained for purposes of id counting and other uses.

### CODE REVIEW

**Comment by vekk513** [comment]
@walkhh @Saerith @vats96ashu @abderisaq 

Also apparently my previous stuff didn't get merged again, my bad I don't know how to get around that, so it includes my other commits from my previous work on sequential ids and all.

**Comment by vekk513** [comment]
No reason, just a habit. I can modify that as well.

**Comment by vekk513** [comment]
Updated, if it looks good feel free to merge so my next branch doesn't have a million previous commits >.>

**Comment by walkhh** [comment]
ok

**Pull request merged**
