### PR TITLE
Feat/gui additions

### PR DESCRIPTION
**Pull request by walkhh**
Made code compilable
Added load/save data functionality
Added buttons on every existing window
Rudimentary login check
Made test classes the same as current master's test classes (they were outdated?)

### CODE REVIEW

**Comment by walkhh** [comment]
Sorry @abderisaq, this branch has been worked on for while and somehow that filename got out of sync. Let's merge your branch to master first, then I will get this branch compatible with it.

**Comment by abderisaq** [comment]
K Thanks

**Comment by walkhh** [comment]
Ok, this is up to date with that recent branch

**Comment by walkhh** [comment]
Probably won't have much time tonight to work on much more

**Pull request merged**
